export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const FETCH_ALL_CUSTOMERS = "FETCH_ALL_CUSTOMERS";
export const UNSET_CUSTOMERS = "UNSET_CUSTOMERS";
